/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 3dRendering.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

const Rendering = (props) => {
  const { nodes, materials } = useGLTF('../../3dRendering.glb')
  return (
    <group {...props} dispose={null} position={props.isMobile ? [-1.5, -1, -1] : [-2, 0, -1]} rotation={[0, 4, 0]} scale={props.isMobile ? 0.8 : 1}>
      <group position={[0.042, -0.7, -0.066]} rotation={[0, 0.611, 0]} scale={2.366}>
        <mesh geometry={nodes.Text001.geometry} material={materials.Material__26} scale={0.025} />
      </group>
      <group position={[-0.288, -2.776, 1.504]} scale={[3.815, 3.815, 3.857]}>
        <mesh geometry={nodes.Text002.geometry} material={materials.Material__25} scale={0.025} />
      </group>
    </group>
  )
}

useGLTF.preload('/3dRendering.glb')

export default Rendering