/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 Monitor.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

const Monitor3D = (props) => {
  const { nodes, materials } = useGLTF('/Monitor.glb')
  return (
    <group {...props} dispose={null} position={[2, 0, 0]} rotation={[0, 90, 0]}>
      <group position={[-0.081, -1.377, 1.427]} rotation={[-Math.PI / 2, 0, 0]} scale={1.59}>
        <mesh geometry={nodes.Box001.geometry} material={materials.Material__26} scale={0.025} />
      </group>
      <group position={[-0.081, -1.377, 1.427]} rotation={[-Math.PI / 2, 0, 0]} scale={1.59}>
        <mesh geometry={nodes.Screen.geometry} material={materials.Material__25} scale={0.025} />
      </group>
      <group position={[0.04, -2.844, 0.434]}>
        <mesh geometry={nodes.Text002.geometry} material={materials.Material__146} scale={0.025} />
      </group>
    </group>
  )
}

useGLTF.preload('/Monitor.glb')

export default Monitor3D