/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 3dRendering.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/3dRendering.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-0.145, -1.709, 0.188]} rotation={[-Math.PI / 2, 0, 0]} scale={2.366}>
        <mesh geometry={nodes.Box001.geometry} material={materials.Material__26} scale={0.025} />
      </group>
      <group position={[0.042, -0.12, -0.066]} rotation={[0, 0.611, 0]} scale={2.366}>
        <mesh geometry={nodes.Text001.geometry} material={materials.Material__26} scale={0.025} />
      </group>
      <group position={[-0.288, -2.776, 1.504]} scale={[3.815, 3.815, 3.857]}>
        <mesh geometry={nodes.Text002.geometry} material={materials.Material__25} scale={0.025} />
      </group>
    </group>
  )
}

useGLTF.preload('/3dRendering.glb')
